### ISSUE TITLE
microservices communicate with each other through event bus?

### ISSUE THREAD

**Issue by soujiro0725** [omearac/reactive-kafka-microservice-template#5]
I have a question.  I am confused with the comment in EventProducer.scala

>   * This actor receives local app events called "ExampleAppEvent"s which are initially published to the
>   * "internal" Akka Event Bus and which he is subscribed to. He then publishes the event messages to the Kafka
>   * topic called AppEventChannel. The idea would be that another microservice is subscribed to
>   * the AppEventChannel topic and can then react to events this microservice emits.

Does this mean a microservice communicates with another through both local event bus and Kafka?
If so, why do I need both?

**Comment by omearac** [comment]
Good question.

The idea is that we have "local" events that describe the runtime behavior of the microservice (such as StartedConsumerStream connection to Kafka) and these are sent around within the single microservice by the Local Akka Message bus. 

From there, we have a local actor (EventProducer) listening in (subscribed) to these AppEvent messages who pipes them externally to Kafka to the topic ExampleAppEvents.

For demonstration, I've also made this microservice subscribe to this same Kafka topic to read these back in but in reality this service would be subscribed to another such topic to react to local app from another service.

Does that clarify things? :)

**Comment by soujiro0725** [comment]
Yes.  It does clarify.  Thanks!
And thanks for your wonderful template!

**Comment by omearac** [comment]
Great! Glad you find it useful !
